/*
 * armguesser location database.
 *
 * Each entry:
 *   id          unique slug
 *   name        English name
 *   hy          Armenian script
 *   translit    Latin transliteration of the Armenian name
 *   lat, lng    WGS84 coordinates (decimal degrees)
 *   region      one of the 11 administrative regions (marzer) incl. Yerevan
 *   category    city | town | village | monastery | church | landmark | memorial |
 *               historical | fortress | lake | natural
 *   difficulty  1 (easy) – 4 (expert)
 *   fact        one-line fun fact shown after the round
 *   population  optional, approximate, for settlements
 */
(function (root) {
  'use strict';

  var L = function (id, name, hy, translit, lat, lng, region, category, difficulty, fact, population) {
    var loc = {
      id: id, name: name, hy: hy, translit: translit,
      lat: lat, lng: lng, region: region, category: category,
      difficulty: difficulty, fact: fact
    };
    if (population) loc.population = population;
    return loc;
  };

  var LOCATIONS = [
    /* ---------------------------------------------------------------- Yerevan */
    L('republic-square', 'Republic Square', 'Հանրապետության հրապարակ', 'Hanrapetutyan hraparak',
      40.1777, 44.5126, 'Yerevan', 'landmark', 1,
      'Designed by Alexander Tamanian, its buildings are clad in pink and yellow tuff, and its fountains "sing" on summer evenings.'),
    L('cascade', 'Cascade Complex', 'Կասկադ', 'Kaskad',
      40.1916, 44.5155, 'Yerevan', 'landmark', 1,
      'The giant limestone stairway climbs 572 steps and hides the Cafesjian Center for the Arts inside.'),
    L('opera', 'Yerevan Opera House', 'Օպերայի և բալետի թատրոն', 'Operayi yev baleti tatron',
      40.1864, 44.5155, 'Yerevan', 'landmark', 1,
      'Tamanian\'s design won a Grand Prix at the 1937 Paris World Exhibition.'),
    L('tsitsernakaberd', 'Tsitsernakaberd Genocide Memorial', 'Ծիծեռնակաբերդ', 'Tsitsernakaberd',
      40.1855, 44.4906, 'Yerevan', 'memorial', 1,
      'Twelve inclined basalt slabs circle the eternal flame, one for each lost province of Western Armenia.'),
    L('mother-armenia', 'Mother Armenia Monument', 'Մայր Հայաստան', 'Mayr Hayastan',
      40.1956, 44.5244, 'Yerevan', 'landmark', 1,
      'The 22 m statue replaced a monument to Stalin in 1967; its pedestal houses a military museum.'),
    L('matenadaran', 'Matenadaran', 'Մատենադարան', 'Matenadaran',
      40.1922, 44.5214, 'Yerevan', 'landmark', 2,
      'It holds over 17,000 manuscripts, one of the richest collections of medieval texts in the world.'),
    L('erebuni', 'Erebuni Fortress', 'Էրեբունի', 'Erebuni',
      40.1396, 44.5365, 'Yerevan', 'fortress', 2,
      'Founded in 782 BC by the Urartian king Argishti I, making Yerevan older than Rome.'),

    /* ---------------------------------------------------------------- Armavir */
    L('etchmiadzin', 'Etchmiadzin Cathedral', 'Էջմիածնի մայր տաճար', 'Ejmiatsni mayr tachar',
      40.1619, 44.2911, 'Armavir', 'church', 1,
      'Often called the oldest cathedral in the world, first built in 301–303 AD.', 46000),
    L('zvartnots', 'Zvartnots Cathedral Ruins', 'Զվարթնոց', 'Zvartnots',
      40.1603, 44.3369, 'Armavir', 'historical', 1,
      'The round 7th-century cathedral collapsed in an earthquake around the 10th century and is now a UNESCO site.'),
    L('sardarapat', 'Sardarapat Memorial', 'Սարդարապատի հուշահամալիր', 'Sardarapati hushahamalir',
      40.0978, 43.9497, 'Armavir', 'memorial', 1,
      'Commemorates the May 1918 battle that halted the Ottoman advance into the Ararat valley.'),
    L('metsamor-npp', 'Metsamor Nuclear Power Plant', 'Մեծամորի ատոմակայան', 'Metsamori atomakayan',
      40.1811, 44.1489, 'Armavir', 'landmark', 2,
      'Armenia\'s only nuclear plant supplies roughly a third of the country\'s electricity.'),
    L('armavir', 'Armavir', 'Արմավիր', 'Armavir',
      40.1545, 44.0380, 'Armavir', 'city', 2,
      'Called Hoktemberyan in Soviet times, the city took the name of Armenia\'s ancient capital in 1995.', 29000),

    /* ----------------------------------------------------------------- Ararat */
    L('khor-virap', 'Khor Virap Monastery', 'Խոր Վիրապ', 'Khor Virap',
      39.8781, 44.5759, 'Ararat', 'monastery', 1,
      'Gregory the Illuminator was held in a pit here for 13 years before converting King Tiridates III.'),
    L('artashat', 'Artashat', 'Արտաշատ', 'Artashat',
      39.9539, 44.5506, 'Ararat', 'city', 2,
      'Named after the ancient capital founded nearby around 176 BC by King Artaxias I.', 20000),
    L('dvin', 'Dvin Archaeological Site', 'Դվին', 'Dvin',
      40.0042, 44.5772, 'Ararat', 'historical', 3,
      'Dvin was Armenia\'s capital from the 4th century until it was ruined by earthquakes and invasions.'),
    L('vedi', 'Vedi', 'Վեդի', 'Vedi',
      39.9106, 44.7278, 'Ararat', 'town', 3,
      'Sits where the vineyards of the Ararat plain meet the dry Urts mountains.', 11000),
    L('ararat-town', 'Ararat', 'Արարատ', 'Ararat',
      39.8306, 44.7050, 'Ararat', 'town', 3,
      'A cement-factory town and one of the closest settlements to the Turkish border.', 20000),
    L('masis', 'Masis', 'Մասիս', 'Masis',
      40.0647, 44.4358, 'Ararat', 'town', 3,
      '"Masis" is the Armenian name for Mount Ararat itself.', 20000),
    L('yeraskh', 'Yeraskh', 'Երասխ', 'Yeraskh',
      39.7630, 44.7970, 'Ararat', 'village', 4,
      'A frontier village wedged between Turkey and Azerbaijan\'s Nakhchivan exclave.'),

    /* ------------------------------------------------------------- Aragatsotn */
    L('amberd', 'Amberd Fortress', 'Ամբերդ', 'Amberd',
      40.3881, 44.2258, 'Aragatsotn', 'fortress', 1,
      'At 2,300 m on Mount Aragats; its name means "fortress in the clouds".'),
    L('saghmosavank', 'Saghmosavank', 'Սաղմոսավանք', 'Saghmosavank',
      40.3785, 44.3963, 'Aragatsotn', 'monastery', 2,
      'The "Monastery of Psalms" sits right on the lip of the Kasagh river gorge.'),
    L('hovhannavank', 'Hovhannavank', 'Հովհաննավանք', 'Hovhannavank',
      40.3446, 44.3883, 'Aragatsotn', 'monastery', 2,
      'Its 13th-century church has a carved tympanum of the Wise and Foolish Virgins.'),
    L('lake-kari', 'Lake Kari', 'Քարի լիճ', 'Kari lich',
      40.4735, 44.1905, 'Aragatsotn', 'lake', 2,
      'A glacial lake at 3,200 m, the usual base camp for climbing Mount Aragats.'),
    L('byurakan', 'Byurakan Observatory', 'Բյուրականի աստղադիտարան', 'Byurakani astghaditaran',
      40.3309, 44.2745, 'Aragatsotn', 'landmark', 3,
      'Founded in 1946 by Viktor Ambartsumian; the Markarian galaxy survey was made here.'),
    L('ashtarak', 'Ashtarak', 'Աշտարակ', 'Ashtarak',
      40.2992, 44.3617, 'Aragatsotn', 'city', 2,
      'Its name means "tower"; the town is split by the Kasagh gorge and a 17th-century bridge.', 18000),
    L('oshakan', 'Oshakan', 'Օշական', 'Oshakan',
      40.2636, 44.3136, 'Aragatsotn', 'village', 3,
      'Burial place of Mesrop Mashtots, creator of the Armenian alphabet.'),
    L('aparan', 'Aparan', 'Ապարան', 'Aparan',
      40.5933, 44.3586, 'Aragatsotn', 'town', 3,
      'At about 1,900 m it is one of Armenia\'s coldest towns, and the site of a 1918 battle.', 6000),
    L('talin', 'Talin', 'Թալին', 'Talin',
      40.3917, 43.8750, 'Aragatsotn', 'town', 3,
      'Its 7th-century cathedral is one of the largest early-medieval churches in Armenia.', 5000),
    L('aruch', 'Aruch', 'Արուճ', 'Aruch',
      40.2878, 44.0875, 'Aragatsotn', 'village', 4,
      'The Aruch cathedral was built in 661–682 by Prince Grigor Mamikonian.'),

    /* ----------------------------------------------------------------- Kotayk */
    L('garni', 'Garni Temple', 'Գառնիի տաճար', 'Garnii tachar',
      40.1127, 44.7302, 'Kotayk', 'historical', 1,
      'The only standing Greco-Roman colonnaded building in the former Soviet Union (1st century AD).'),
    L('geghard', 'Geghard Monastery', 'Գեղարդ', 'Geghard',
      40.1406, 44.8181, 'Kotayk', 'monastery', 1,
      'Partly carved into the cliff and named after the spear (geghard) that pierced Christ.'),
    L('symphony-of-stones', 'Symphony of Stones', 'Քարերի սիմֆոնիա', 'Kareri simfonia',
      40.1135, 44.7340, 'Kotayk', 'natural', 2,
      'Hexagonal basalt columns line the Azat gorge below Garni like giant organ pipes.'),
    L('kecharis', 'Kecharis Monastery, Tsaghkadzor', 'Կեչառիս', 'Kecharis',
      40.5372, 44.7200, 'Kotayk', 'monastery', 2,
      'It stands in Tsaghkadzor, Armenia\'s ski resort, whose name means "valley of flowers".'),
    L('hrazdan', 'Hrazdan', 'Հրազդան', 'Hrazdan',
      40.4978, 44.7664, 'Kotayk', 'city', 2,
      'Named after the river that drains Lake Sevan and flows down to Yerevan.', 40000),
    L('abovyan', 'Abovyan', 'Աբովյան', 'Abovyan',
      40.2739, 44.6256, 'Kotayk', 'city', 3,
      'Named after Khachatur Abovyan, father of modern Armenian literature.', 43000),
    L('charentsavan', 'Charentsavan', 'Չարենցավան', 'Charentsavan',
      40.4025, 44.6419, 'Kotayk', 'town', 3,
      'A Soviet industrial town named after the poet Yeghishe Charents.', 20000),
    L('arzni', 'Arzni', 'Արզնի', 'Arzni',
      40.2983, 44.5889, 'Kotayk', 'village', 3,
      'A famous Soviet spa resort built around mineral springs in the Hrazdan gorge.'),
    L('bjni', 'Bjni', 'Բջնի', 'Bjni',
      40.4589, 44.6503, 'Kotayk', 'village', 3,
      'Known across Armenia for the Bjni mineral water bottled here.'),
    L('ptghni', 'Ptghnavank', 'Պտղնավանք', 'Ptghnavank',
      40.2567, 44.5853, 'Kotayk', 'church', 4,
      'A roofless 6th–7th century basilica in a small village just north of Yerevan.'),
    L('ddmashen', 'Ddmashen', 'Դդմաշեն', 'Ddmashen',
      40.5703, 44.8203, 'Kotayk', 'village', 4,
      'Its name means "pumpkin village"; its 7th-century church is remarkably intact.'),

    /* ------------------------------------------------------------ Gegharkunik */
    L('sevanavank', 'Sevanavank', 'Սևանավանք', 'Sevanavank',
      40.5643, 45.0122, 'Gegharkunik', 'monastery', 1,
      'Built in 874 on an island that became a peninsula when Soviet engineers lowered Lake Sevan.'),
    L('noratus', 'Noratus Cemetery', 'Նորատուս', 'Noratus',
      40.3756, 45.1797, 'Gegharkunik', 'historical', 2,
      'Holds the largest surviving field of medieval khachkars (cross-stones) — nearly 1,000.'),
    L('hayravank', 'Hayravank', 'Հայրավանք', 'Hayravank',
      40.4378, 45.1117, 'Gegharkunik', 'monastery', 3,
      'A small 9th–12th century monastery right on the western shore of Lake Sevan.'),
    L('gavar', 'Gavar', 'Գավառ', 'Gavar',
      40.3589, 45.1267, 'Gegharkunik', 'city', 3,
      'The regional capital was known as Nor Bayazet and later Kamo.', 20000),
    L('sevan-town', 'Sevan', 'Սևան', 'Sevan',
      40.5486, 44.9486, 'Gegharkunik', 'town', 2,
      'Founded in 1842 by Russian Molokans as Yelenovka.', 19000),
    L('martuni', 'Martuni', 'Մարտունի', 'Martuni',
      40.1400, 45.3067, 'Gegharkunik', 'town', 3,
      'A lakeside town on the southern shore of Sevan, close to the Armaghan volcano.', 12000),
    L('vardenis', 'Vardenis', 'Վարդենիս', 'Vardenis',
      40.1797, 45.7206, 'Gegharkunik', 'town', 3,
      'Its name means "rose-bearing"; it sits near the eastern tip of Lake Sevan.', 12000),
    L('chambarak', 'Chambarak', 'Ճամբարակ', 'Chambarak',
      40.5942, 45.3500, 'Gegharkunik', 'town', 4,
      'Called Krasnoselsk in Soviet times, it lies in forested hills north-east of Sevan.', 6000),
    L('lchashen', 'Lchashen', 'Լճաշեն', 'Lchashen',
      40.5186, 44.9328, 'Gegharkunik', 'village', 4,
      'Bronze-Age wooden wagons were found here when the lake level dropped.'),

    /* ------------------------------------------------------------------- Lori */
    L('vanadzor', 'Vanadzor', 'Վանաձոր', 'Vanadzor',
      40.8128, 44.4883, 'Lori', 'city', 2,
      'Armenia\'s third-largest city, called Kirovakan during the Soviet era.', 75000),
    L('haghpat', 'Haghpat Monastery', 'Հաղպատ', 'Haghpat',
      41.0937, 44.7117, 'Lori', 'monastery', 1,
      'A UNESCO World Heritage monastery founded in the 10th century by Queen Khosrovanuysh.'),
    L('sanahin', 'Sanahin Monastery', 'Սանահին', 'Sanahin',
      41.0868, 44.6663, 'Lori', 'monastery', 2,
      'The village is the birthplace of Artem Mikoyan, co-designer of the MiG fighter jet.'),
    L('alaverdi', 'Alaverdi', 'Ալավերդի', 'Alaverdi',
      41.0978, 44.6731, 'Lori', 'town', 3,
      'A copper-smelting town in the Debed canyon, linked to Sanahin by a Soviet cable car.', 12000),
    L('akhtala', 'Akhtala Monastery', 'Ախթալա', 'Akhtala',
      41.1511, 44.7639, 'Lori', 'monastery', 3,
      'Famous for vivid 13th-century frescoes inside a fortified cliff-top complex.'),
    L('odzun', 'Odzun', 'Օձուն', 'Odzun',
      41.0517, 44.6147, 'Lori', 'village', 3,
      'Its 6th-century basilica stands on a plateau high above the Debed canyon.'),
    L('kobayr', 'Kobayr Monastery', 'Քոբայր', 'Kobayr',
      41.0056, 44.6364, 'Lori', 'monastery', 4,
      'A half-ruined cliffside monastery with Georgian-style frescoes, reached by a steep path.'),
    L('stepanavan', 'Stepanavan', 'Ստեփանավան', 'Stepanavan',
      41.0075, 44.3867, 'Lori', 'town', 3,
      'The medieval fortress of Lori Berd stands on a gorge-bound promontory just outside town.', 13000),
    L('spitak', 'Spitak', 'Սպիտակ', 'Spitak',
      40.8322, 44.2672, 'Lori', 'town', 3,
      'Almost completely destroyed in the 1988 earthquake and rebuilt with international help.', 12000),
    L('tashir', 'Tashir', 'Տաշիր', 'Tashir',
      41.1206, 44.2847, 'Lori', 'town', 4,
      'A high-plateau town near the Georgian border, well known for its cheese.', 7000),
    L('gyulagarak', 'Gyulagarak', 'Գյուլագարակ', 'Gyulagarak',
      40.9667, 44.4700, 'Lori', 'village', 4,
      'Close to a grove of centuries-old pines planted by Russian settlers in the 19th century.'),
    L('fioletovo', 'Fioletovo', 'Ֆիոլետովո', 'Fioletovo',
      40.7228, 44.7178, 'Lori', 'village', 4,
      'Founded by Russian Molokans in the 1840s who still keep their traditional way of life.'),
    L('dsegh', 'Dsegh', 'Դսեղ', 'Dsegh',
      40.9611, 44.6503, 'Lori', 'village', 4,
      'Birthplace of Hovhannes Tumanyan, Armenia\'s beloved national poet.'),

    /* ----------------------------------------------------------------- Shirak */
    L('gyumri', 'Gyumri', 'Գյումրի', 'Gyumri',
      40.7894, 43.8475, 'Shirak', 'city', 1,
      'Armenia\'s second city (once Alexandropol and Leninakan), famous for black tuff houses and its sense of humour.', 112000),
    L('marmashen', 'Marmashen Monastery', 'Մարմաշեն', 'Marmashen',
      40.8580, 43.7822, 'Shirak', 'monastery', 3,
      'Built in the 10th–11th centuries from red tuff beside the Akhurian river.'),
    L('harichavank', 'Harichavank', 'Հառիճավանք', 'Harichavank',
      40.5975, 43.9942, 'Shirak', 'monastery', 3,
      'Once the summer residence of the Catholicos of All Armenians.'),
    L('artik', 'Artik', 'Արթիկ', 'Artik',
      40.6172, 43.9758, 'Shirak', 'town', 3,
      'Known for its pink tuff quarries, the stone used on many Yerevan buildings.', 17000),
    L('maralik', 'Maralik', 'Մարալիկ', 'Maralik',
      40.5758, 43.8706, 'Shirak', 'town', 4,
      'A small town on the Shirak plateau at the foot of Mount Aragats\' western slopes.', 5000),
    L('amasia', 'Amasia', 'Ամասիա', 'Amasia',
      40.9547, 43.7869, 'Shirak', 'village', 4,
      'A high, windswept village on the northern Shirak plateau near the Turkish border.'),
    L('ashotsk', 'Ashotsk', 'Աշոցք', 'Ashotsk',
      41.0344, 43.8625, 'Shirak', 'village', 4,
      'One of the coldest places in Armenia, where winter nights can fall below −40 °C.'),
    L('lake-arpi', 'Lake Arpi', 'Արփի լիճ', 'Arpi lich',
      41.0500, 43.6167, 'Shirak', 'lake', 4,
      'A reservoir and national park that is a key stop for migrating birds.'),

    /* ----------------------------------------------------------------- Tavush */
    L('dilijan', 'Dilijan', 'Դիլիջան', 'Dilijan',
      40.7408, 44.8636, 'Tavush', 'town', 1,
      'Nicknamed "Armenian Switzerland" for its forests and restored 19th-century old town.', 17000),
    L('haghartsin', 'Haghartsin Monastery', 'Հաղարծին', 'Haghartsin',
      40.8014, 44.8903, 'Tavush', 'monastery', 2,
      'Tucked into the forest north of Dilijan; restored with funding from a Sheikh of Sharjah.'),
    L('goshavank', 'Goshavank', 'Գոշավանք', 'Goshavank',
      40.7295, 44.9978, 'Tavush', 'monastery', 2,
      'Founded in 1188 by Mkhitar Gosh, author of the first Armenian law code.'),
    L('lake-parz', 'Lake Parz', 'Պարզ լիճ', 'Parz lich',
      40.7508, 44.9594, 'Tavush', 'lake', 2,
      '"Parz" means "clear"; the lake is a favourite hiking stop in Dilijan National Park.'),
    L('ijevan', 'Ijevan', 'Իջևան', 'Ijevan',
      40.8756, 45.1492, 'Tavush', 'town', 3,
      'Its name means "inn"; it was a stop on an old caravan route along the Aghstev river.', 21000),
    L('makaravank', 'Makaravank', 'Մակարավանք', 'Makaravank',
      40.9714, 45.1272, 'Tavush', 'monastery', 4,
      'Its churches are covered in some of the finest ornamental stone carving in Armenia.'),
    L('yenokavan', 'Yenokavan', 'Ենոքավան', 'Yenokavan',
      40.9219, 45.1142, 'Tavush', 'village', 4,
      'A forest village above a canyon full of caves, zip-lines and the Lastiver hermitage.'),
    L('noyemberyan', 'Noyemberyan', 'Նոյեմբերյան', 'Noyemberyan',
      41.1722, 44.9997, 'Tavush', 'town', 4,
      'A small hill town near the Georgian border, surrounded by orchards.', 5000),
    L('berd', 'Berd', 'Բերդ', 'Berd',
      40.8808, 45.3875, 'Tavush', 'town', 4,
      'Named after its 17th-century fortress, Tavush Berd.', 8000),

    /* ------------------------------------------------------------ Vayots Dzor */
    L('noravank', 'Noravank Monastery', 'Նորավանք', 'Noravank',
      39.6842, 45.2330, 'Vayots Dzor', 'monastery', 1,
      'Its two-storey church by master Momik is reached by narrow stone steps with no railing.'),
    L('jermuk', 'Jermuk', 'Ջերմուկ', 'Jermuk',
      39.8406, 45.6725, 'Vayots Dzor', 'town', 1,
      'A spa town famous for mineral water and a 70 m waterfall.', 5000),
    L('areni', 'Areni', 'Արենի', 'Areni',
      39.7222, 45.1833, 'Vayots Dzor', 'village', 2,
      'The nearby Areni-1 cave held the world\'s oldest known winery and oldest leather shoe.'),
    L('selim', 'Selim Caravanserai', 'Սելիմի քարավանատուն', 'Selimi karavanatun',
      39.9475, 45.2372, 'Vayots Dzor', 'historical', 2,
      'Built in 1332 on the Silk Road at about 2,400 m on the Vardenyats pass.'),
    L('yeghegnadzor', 'Yeghegnadzor', 'Եղեգնաձոր', 'Yeghegnadzor',
      39.7611, 45.3333, 'Vayots Dzor', 'town', 3,
      'Its name means "reed gorge"; it is the smallest regional capital in Armenia.', 7000),
    L('gndevank', 'Gndevank', 'Գնդեվանք', 'Gndevank',
      39.7583, 45.6092, 'Vayots Dzor', 'monastery', 3,
      'A 10th-century monastery hidden in the Arpa gorge on the road to Jermuk.'),
    L('vayk', 'Vayk', 'Վայք', 'Vayk',
      39.6889, 45.4667, 'Vayots Dzor', 'town', 4,
      'A small town on the Arpa river along the main road south to Syunik.', 5000),
    L('shatin', 'Shatin', 'Շատին', 'Shatin',
      39.8358, 45.3025, 'Vayots Dzor', 'village', 4,
      'The gateway to the Yeghegis valley, a good place to spot wild bezoar goats.'),
    L('yeghegis', 'Yeghegis', 'Եղեգիս', 'Yeghegis',
      39.8722, 45.3708, 'Vayots Dzor', 'village', 4,
      'Home to a rare medieval Jewish cemetery with Hebrew inscriptions.'),

    /* ----------------------------------------------------------------- Syunik */
    L('tatev', 'Tatev Monastery', 'Տաթևի վանք', 'Tatevi vank',
      39.3797, 46.2500, 'Syunik', 'monastery', 1,
      'Reached by the 5.7 km "Wings of Tatev", once the world\'s longest reversible cable car.'),
    L('goris', 'Goris', 'Գորիս', 'Goris',
      39.5111, 46.3383, 'Syunik', 'town', 2,
      'Its old town is dotted with cave dwellings carved into conical rock pillars.', 20000),
    L('kapan', 'Kapan', 'Կապան', 'Kapan',
      39.2076, 46.4058, 'Syunik', 'city', 2,
      'The capital of Syunik, surrounded by forested mountains and copper mines.', 42000),
    L('karahunj', 'Zorats Karer (Carahunge)', 'Զորաց քարեր', 'Zorats karer',
      39.5514, 46.0286, 'Syunik', 'historical', 2,
      'Sometimes called the "Armenian Stonehenge": over 200 standing stones, some with drilled holes.'),
    L('khndzoresk', 'Khndzoresk', 'Խնձորեսկ', 'Khndzoresk',
      39.5058, 46.4353, 'Syunik', 'village', 2,
      'Its abandoned cave village is reached across a 160 m swinging footbridge.'),
    L('sisian', 'Sisian', 'Սիսիան', 'Sisian',
      39.5211, 46.0322, 'Syunik', 'town', 3,
      'The 7th-century church of Sisavan overlooks the town on the Vorotan river.', 14000),
    L('shaki', 'Shaki Waterfall', 'Շաքիի ջրվեժ', 'Shakii jrvezh',
      39.5520, 45.9950, 'Syunik', 'natural', 3,
      'An 18 m waterfall that legend says was formed from the tears of a girl named Shaki.'),
    L('meghri', 'Meghri', 'Մեղրի', 'Meghri',
      38.9031, 46.2447, 'Syunik', 'town', 3,
      'Armenia\'s southernmost town, beside the Iranian border and famous for pomegranates.', 4500),
    L('agarak', 'Agarak', 'Ագարակ', 'Agarak',
      38.8617, 46.1903, 'Syunik', 'town', 4,
      'A mining town on the Araks river, facing Iran across the border crossing.', 4500),
    L('kajaran', 'Kajaran', 'Քաջարան', 'Kajaran',
      39.1508, 46.1603, 'Syunik', 'town', 4,
      'Home to one of the world\'s largest copper-molybdenum deposits.', 7000),
    L('angeghakot', 'Angeghakot', 'Անգեղակոթ', 'Angeghakot',
      39.5625, 45.9406, 'Syunik', 'village', 4,
      'Its name means "vulture\'s nest"; it is one of Syunik\'s oldest villages.'),
    L('vorotnavank', 'Vorotnavank', 'Որոտնավանք', 'Vorotnavank',
      39.4883, 45.9767, 'Syunik', 'monastery', 4,
      'A fortified 11th-century monastery on the edge of the Vorotan gorge.')
  ];

  root.ARM_LOCATIONS = LOCATIONS;
  if (typeof module !== 'undefined' && module.exports) module.exports = LOCATIONS;
})(typeof window !== 'undefined' ? window : globalThis);
